# In order for the player to see their name, please install the Player extension for PlaceholderAPI.
messages:
  Prefix: '&9&lVibeツ&8 » '
  ProfileLoadedMessage: 'Welcome back %player_name%'
  ProfileCreatedMessage: 'Welcome %player_name%'
  ConfigReloaded: '&aReloaded config.'
  NoPermissionMessage: '&cYou do not have permission!'
  IDontWantSpeedMessage: '&cDisabled speed.'
  IWantSpeedMessage: '&aRe-enabled speed.'
  BuildEnabled: '&aTurned on build mode.'
  BuildDisabled: '&cTurned off build mode.'
  IncorrectUsage: '&cThe proper usage for this command is ' #Argument would go after this line.
  HubSetMessage: '&7Hub location has been set to your current location! &cYou may need to reboot the server for this change to take effect.'
  ServerIP: '&9&lvibemarket.org'
#This section controls where to spawn players, this section should never need to be touched directly, please use /sethub in game to change these values!
coordinates:
  hub:
    world: "Hub2021"
    x: 0.5
    y: 67.0
    z: 0.5
    pitch: 0.0
    yaw: -90.0

uuids:
  minauuid: 40ef6ecc-b56f-41f9-bfb1-ec7b7300bfa4
  kevinuuid: a948c50c-ede2-4dfa-9b6c-688daf22197c
  andreauuid: 8bab5cd7-e97f-44bc-839f-c7e54461de20

#This section controls the names of the NPCs that the plugin will search for to tp you to another server.
citizens:
  npcs:
    survival: "§a§lSurvival §7(Right Click)"
    skyblock: "§b§lSkyblock §7(Coming Soon)"
    creative: "§6§lCreative §7(Coming Soon)"
    comingsoon: "§c§lComing Soon §7(Right Click)"

#If a servers version changes, you can update it here. This may require you to reboot the server.
versions:
  survival: "1.19.3"
  creative: "1.19.3"
  skyblock: "1.19.3"
  build: "1.19.3"
  dev: "1.17.1"
  limbo: "1.7-1.19.3"
