messages:
  Prefix: '&9&lVibeツ &8» '
  ProfileLoadedMessage: '&aProfile loaded. Welcome back %player_name%'
  ProfileCreatedMessage: '&aProfile created. Welcome %player_name%'
  ConfigReloaded: '&aReloaded config.'
  NoPermissionMessage: '&cYou do not have permission!'
  IDontWantSpeedMessage: '&cDisabled speed.'
  IWantSpeedMessage: '&aRe-enabled speed.'
  BuildEnabled: '&aTurned on build mode.'
  BuildDisabled: '&cTurned off build mode.'
  IncorrectUsage: '&cThe proper usage for this command is '
  HubSetMessage: '&7Hub location has been set to your current location!'
  ServerIP: '&9&lvibemarket.org'
  VSpeedInvalidArgs: '&cInvalid arguments! Correct usage is /vspeed on & /vspeed off'
coordinates:
  hub:
    world: "Hub2021"
    x: 0.5
    y: 67
    z: 0.5
    pitch: -2.550001
    yaw: -90.59805
permissions:
  ClearInventoryBypassPermission: hub.clearinventory.bypass
  SetHubPermission: vibe.sethub
  ReloadConfigPermission: vibe.reloadconfig
  BuildCommandPermission: vibe.build
uuids:
  minauuid: 40ef6ecc-b56f-41f9-bfb1-ec7b7300bfa4
  kevinuuid: a948c50c-ede2-4dfa-9b6c-688daf22197c
  andreauuid: 8bab5cd7-e97f-44bc-839f-c7e54461de20