name: VibeHub
version: 1.4.0
authors: [ ItsCryptic, MasterDash5 ]
api-version: 1.17
main: me.kevind.vibehub.VibeHub
softdepend: [ HolographicDisplays, WorldGuard, Citizens]
depend: [ PlaceholderAPI, LuckPerms ]
commands:
  hubreload:
    description: Reloads Hub
    aliases:
      - "hr"
      - "reloadhub"
  build:
    description: Toggle build mode for Hub
    aliases:
      - b
  vspeed:
    description: Old speed setting command for Hub.
    aliases:
      - "vs"
  sethub:
    description: Sets the Hub
    aliases:
      - "sh"
  scoreboard:
    description: Turns on and off the scoreboard.
  actionbar:
    description: Turns on and off the actionbar.
  particles:
    description: Opens the particle selector
  cosmetics:
    description: Opens cosmetic selector