name: VibeHub
version: 1.0.5
author: ItsCryptic
api-version: 1.17
main: me.kevind.main.VibeHub
softdepend: [HolographicDisplays]
depend: [PlaceholderAPI]
commands:
  hubreload:
  build:
    description: Toggle build mode for Hub
    aliases:
      - b
  vspeed:
  sethub: