name: VibeHub
version: 1.2.4
author: ItsCryptic
api-version: 1.17
main: me.kevind.VibeHub
softdepend: [ HolographicDisplays, WorldGuard, Citizens, GadgetsMenu ]
depend: [ PlaceholderAPI, LuckPerms ]
commands:
  hubreload:
    description: Reloads Hub
    aliases:
      - "hr"
      - "reloadhub"
  build:
    description: Toggle build mode for Hub
    aliases:
      - b
  vspeed:
    description: Old speed setting command for Hub.
    aliases:
      - "vs"
  sethub:
    description: Sets the Hub
    aliases:
      - "sh"
  iteminfo:
    description: Shows information about the item you're currently holding
    aliases:
      - "ii"
  scoreboard:
    description: Turns on and off the scoreboard.
  actionbar:
    description: Turns on and off the actionbar.
  particles:
    description: Opens the particle selector
  cosmetics:
    description: Opens cosmetic selector